In [1]:
import pandas as pd
import re
from pathlib import Path

In [2]:
df = pd.read_csv("../data/raw/hdb_resale_2017_onwards.csv")
df.head()

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,remaining_lease,resale_price
0,2017-01,ANG MO KIO,2 ROOM,406,ANG MO KIO AVE 10,10 TO 12,44.0,Improved,1979,61 years 04 months,232000.0
1,2017-01,ANG MO KIO,3 ROOM,108,ANG MO KIO AVE 4,01 TO 03,67.0,New Generation,1978,60 years 07 months,250000.0
2,2017-01,ANG MO KIO,3 ROOM,602,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,1980,62 years 05 months,262000.0
3,2017-01,ANG MO KIO,3 ROOM,465,ANG MO KIO AVE 10,04 TO 06,68.0,New Generation,1980,62 years 01 month,265000.0
4,2017-01,ANG MO KIO,3 ROOM,601,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,1980,62 years 05 months,265000.0

In [3]:
df = df[['resale_price', 'month', 'town', 'flat_type', 'block', 'street_name', 'storey_range',
       'floor_area_sqm', 'flat_model', 'lease_commence_date',
       'remaining_lease']]

In [4]:
df.isna().sum()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 231870 entries, 0 to 231869
Data columns (total 11 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   resale_price         231870 non-null  float64
 1   month                231870 non-null  str
 2   town                 231870 non-null  str
 3   flat_type            231870 non-null  str
 4   block                231870 non-null  str
 5   street_name          231870 non-null  str
 6   storey_range         231870 non-null  str
 7   floor_area_sqm       231870 non-null  float64
 8   flat_model           231870 non-null  str
 9   lease_commence_date  231870 non-null  int64
 10  remaining_lease      231870 non-null  str
dtypes: float64(2), int64(1), str(8)
memory usage: 35.8 MB

In [5]:
df["month"] = pd.to_datetime(df["month"])
df["floor_area_sqm"] = pd.to_numeric(df["floor_area_sqm"], errors="coerce")
df["lease_commence_date"] = pd.to_numeric(df["lease_commence_date"], errors="coerce")
df["resale_price"] = pd.to_numeric(df["resale_price"], errors="coerce")

In [6]:
def parse_remaining_lease(value):
    """
    Convert remaining lease text into total months.

    Examples:
    '94 years 08 months' -> 1136
    '61 years' -> 732
    """
    if pd.isna(value):
        return None

    value = str(value).lower()

    years = 0
    months = 0

    year_match = re.search(r"(\d+)\s*years?", value)
    month_match = re.search(r"(\d+)\s*months?", value)

    if year_match:
        years = int(year_match.group(1))

    if month_match:
        months = int(month_match.group(1))

    return years * 12 + months


def parse_storey_midpoint(value):
    """
    Convert storey range into midpoint.

    Example:
    '04 TO 06' -> 5
    """
    if pd.isna(value):
        return None

    numbers = re.findall(r"\d+", str(value))

    if len(numbers) >= 2:
        low = int(numbers[0])
        high = int(numbers[1])
        return (low + high) / 2

    return None

In [7]:
df["remaining_lease_months"] = df["remaining_lease"].apply(parse_remaining_lease)

df["remaining_lease_years"] = (
    df["remaining_lease_months"] / 12
)

df["storey_midpoint"] = (
    df["storey_range"].apply(parse_storey_midpoint)
)

df["price_per_sqm"] = (
    df["resale_price"] / df["floor_area_sqm"]
)

df["transaction_year"] = df["month"].dt.year
df["transaction_month"] = df["month"].dt.month

df["flat_age"] = (
    df["transaction_year"] - df["lease_commence_date"]
)

df.head()

,resale_price,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,remaining_lease,remaining_lease_months,remaining_lease_years,storey_midpoint,price_per_sqm,transaction_year,transaction_month,flat_age
0,232000.0,2017-01-01,ANG MO KIO,2 ROOM,406,ANG MO KIO AVE 10,10 TO 12,44.0,Improved,1979,61 years 04 months,736,61.333333,11.0,5272.727273,2017,1,38
1,250000.0,2017-01-01,ANG MO KIO,3 ROOM,108,ANG MO KIO AVE 4,01 TO 03,67.0,New Generation,1978,60 years 07 months,727,60.583333,2.0,3731.343284,2017,1,39
2,262000.0,2017-01-01,ANG MO KIO,3 ROOM,602,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,1980,62 years 05 months,749,62.416667,2.0,3910.447761,2017,1,37
3,265000.0,2017-01-01,ANG MO KIO,3 ROOM,465,ANG MO KIO AVE 10,04 TO 06,68.0,New Generation,1980,62 years 01 month,745,62.083333,5.0,3897.058824,2017,1,37
4,265000.0,2017-01-01,ANG MO KIO,3 ROOM,601,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,1980,62 years 05 months,749,62.416667,2.0,3955.223881,2017,1,37

In [8]:
df.columns

Index(['resale_price', 'month', 'town', 'flat_type', 'block', 'street_name',
       'storey_range', 'floor_area_sqm', 'flat_model', 'lease_commence_date',
       'remaining_lease', 'remaining_lease_months', 'remaining_lease_years',
       'storey_midpoint', 'price_per_sqm', 'transaction_year',
       'transaction_month', 'flat_age'],
      dtype='str')

In [9]:
df = df[['resale_price', 'month', 'town', 'flat_type', 'block', 'street_name',
       'storey_midpoint','floor_area_sqm', 'flat_model',
       'remaining_lease_months', 'remaining_lease_years', 'flat_age',
       'price_per_sqm', 'transaction_year', 'transaction_month']]

In [10]:
df.head()

,resale_price,month,town,flat_type,block,street_name,storey_midpoint,floor_area_sqm,flat_model,remaining_lease_months,remaining_lease_years,flat_age,price_per_sqm,transaction_year,transaction_month
0,232000.0,2017-01-01,ANG MO KIO,2 ROOM,406,ANG MO KIO AVE 10,11.0,44.0,Improved,736,61.333333,38,5272.727273,2017,1
1,250000.0,2017-01-01,ANG MO KIO,3 ROOM,108,ANG MO KIO AVE 4,2.0,67.0,New Generation,727,60.583333,39,3731.343284,2017,1
2,262000.0,2017-01-01,ANG MO KIO,3 ROOM,602,ANG MO KIO AVE 5,2.0,67.0,New Generation,749,62.416667,37,3910.447761,2017,1
3,265000.0,2017-01-01,ANG MO KIO,3 ROOM,465,ANG MO KIO AVE 10,5.0,68.0,New Generation,745,62.083333,37,3897.058824,2017,1
4,265000.0,2017-01-01,ANG MO KIO,3 ROOM,601,ANG MO KIO AVE 5,2.0,67.0,New Generation,749,62.416667,37,3955.223881,2017,1

In [11]:
df.to_csv("../data/processed/hdb_resale_cleaned.csv", index=False)